import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/lib/Providers";
import "@mantine/core/styles.css";
// import { MantineProvider, createTheme } from "@mantine/core";

// const theme = createTheme({
//   colorScheme: "light",
// });

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
