import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "@/lib/Providers";
//theme
import "primereact/resources/themes/lara-light-indigo/theme.css";

//core
import "primereact/resources/primereact.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Ruang Games",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <Providers>
      <html lang="en">
        <body className={inter.className}>{children}</body>
      </html>
    </Providers>
  );
}
